name: Preview CI
on: [ deployment_status ]
jobs:
  staging-tests:
    name: Run API tests
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Print Github Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Run tests
        run: npx yarn test:integration
        env:
          STAGING_URL: ${{ github.event.deployment_status.target_url }}