name: Preview CI
on: [push, deployment, deployment_status]
jobs:
  show-event:
    runs-on: ubuntu-latest
    steps:
      - name: Print Github Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"