name: Preview CI
on: [ push, deployment, deployment_status ]
jobs:
  staging-tests:
    name: Run API tests against preview deployments
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Print Github Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Checkout code
        uses: actions/checkout@v2
        env:
          STAGING_URL: ${{ github.event.deployment_status.target_url }}
      - name: Run tests
        run: yarn test:integration